# Generated by Django 6.0.5 on 2026-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='query_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='total_query_time_ms',
            field=models.FloatField(default=0),
        ),
    ]
