# Generated by Django 6.0.5 on 2026-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_requestmetric_query_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='exception_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='exception_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='has_exception',
            field=models.BooleanField(default=False),
        ),
    ]
