# Generated by Django 6.0.5 on 2026-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_requestmetric_exception_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='is_slow',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
