# Generated by Django 6.0.5 on 2026-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0004_requestmetric_is_slow'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='route',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='view_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['route'], name='profiler_re_route_f743d1_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['status_code'], name='profiler_re_status__151b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['created_at'], name='profiler_re_created_fc9098_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['is_slow'], name='profiler_re_is_slow_878488_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['has_exception'], name='profiler_re_has_exc_5742cb_idx'),
        ),
    ]
