# Generated by Django 6.0.5 on 2026-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0005_requestmetric_ip_address_requestmetric_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='has_n_plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='n_plus_one_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
