# Generated by Django 6.0.5 on 2026-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0006_requestmetric_has_n_plus_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=500)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('total_requests', models.IntegerField(default=0)),
                ('avg_response_ms', models.FloatField(default=0)),
                ('p95_response_ms', models.FloatField(default=0)),
                ('max_response_ms', models.FloatField(default=0)),
                ('min_response_ms', models.FloatField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('slow_count', models.IntegerField(default=0)),
                ('n_plus_one_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'window_start'], name='profiler_en_route_97ec83_idx'), models.Index(fields=['window_start'], name='profiler_en_window__25116c_idx')],
                'unique_together': {('route', 'window_start')},
            },
        ),
    ]
